### ISSUE TITLE
Make mavlink interface generation agnostic to build tool.

### ISSUE THREAD

**Issue by tribbloid** [project-condor/mavigator#15]
Rightht now the mavlink binding part is only available as an sbt-plugin, which makes it harder to be integrated with maven & gradle projects. 

It also cannot be properly parsed by IntelliJ IDEA. (Eclipse is good for pure scala programs but IntelliJ is widely regarded as more adept at handling large projects)

I would suggest making it an executable utility that can generate classes in the source folder. Similar to protocol buffer's java binding. Since mavlink dialect xml rarely changed, the generated code can be pushed as part of the code base, and doesn't have to be updated often.

**Comment by jodersky** [comment]
Hi and thanks for sharing your concerns.
Mavigator uses `sbt` as its build tool and hence `sbt-mavlink` to generate Scala representations of MAVLink messages. This setup should not interfere with your editor of choice (I personally use ensime, but IntelliJ should work just as well if you run "sbt compile" once before), since bindings are in fact generated as source files, in `target/scala-2.xx/src_managed`. These "managed" sources are compiled just like any other source file and included in the resulting jars, therefore also making Mavigator usable as any other Scala library.

Can you share a bit more about your use case and what is blocking it? Are you trying to build this project with maven or gradle, or wanting to use sbt-mavlink in a different project without being tied to sbt?

In the latter case, I would suggest checking out the official [MAVLink project](https://github.com/mavlink/mavlink); they have generators for C, Python and Java. If you're looking for the same kind of message bindings for scala but without sbt, you should still check out the [sbt-mavlink project](https://github.com/project-condor/sbt-mavlink): it is divided into an sbt-specific "plugin" project and a non-sbt-dependent  "library" project. The library project is available on bintray jcenter and should be easily integrable into any other tool.

**Comment by tribbloid** [comment]
Hi Jacob, thanks a lot for your answer: My case is to use sbt-mavlink plugin on a maven-based project. (detail in [this github issue](https://github.com/tribbloid/spookystuff/issues/54)). Sorry I wasn't aware that sbt-mavlink has a library mode, in which case I can just generate java-binding for different hardware beforehand. Or alternatively, if mavigator-binding is pre-built for ardupilot & PX4 I can just include it directly.

I found the main API of sbt-mavlink generator at https://github.com/project-condor/sbt-mavlink/blob/master/mavlink-library/src/test/scala/com/github/jodersky/mavlink/MainTest.scala. That should solve all my problem, case resolved.

**Comment by tribbloid** [comment]
Also, may I have another suggestion? If mavigator has an intermediate abstraction layer that converts high-level vehicle functions (e.g. arm/waypointTo/barrelRoll etc.) to mavlink message and send through telemetric. Then it would be nice to set up an integration test environment though SITL, like this:

https://github.com/dronekit/dronekit-python/tree/master/dronekit/test/sitl

For drone software all crashes are real, yet I can't find any kind of integration test except the one in python. If you believe this won't incur drastic changes (unlike dronekit-android) I'll start reading your code. Otherwise it may be easier just calling PythonUDF.

**Comment by jodersky** [comment]
> For drone software all crashes are real [...]

that's true :)
Mavigator is currently only able to render basic MAVLink messages in a web ui. More complexity, such as being able to send commands to drones will definitely require testing!

**Comment by tribbloid** [comment]
I have a few unrelated questions, let's discuss further on gitter: https://gitter.im/project-condor/project-condor
