### ISSUE TITLE
Redesign Cockpit Layout (RFC)

### ISSUE THREAD

**Issue by jodersky** [project-condor/mavigator#8]
## Problem

The current UI positioning is the result of a quick and dirty implementation. It would be great to implement a design that is both
1. well structured
2. keeps a certain degree of flexibility to accomodate user preferences
## Idea

My initial idea addressing this issue is to reposition elements into a region-based layout according the following image:
![design](https://cloud.githubusercontent.com/assets/1007012/6814551/e6c35cac-d27f-11e4-9800-6c18452cf66e.png)
Initially, the "Normal View" is shown, i.e. the main cockpit with all instruments and video feed. A second layout, the "Detailed View" can be brought up to access some detailed settings or views. In this way the main panel is always visible to the user.

Furthermore, to accomodate users' preferences, they should be able to reposition individual instruments into the different region. I.e. a user may chose to move the communication panel from the right to the left or to completely hide the video feed.
## Implementation

Being no expert in web-design, two solutions come into my mind:
1. Using the standard bootstrap grid layout
2. Using flexboxes
   Since the cockpit differs from most webapps in that it has a height constraint of 100%, using the bootstrap grid system feels clunky. I find the second solution is the most modern and elegant way to handle such a layout.
## Request For Comments

This is a just a first idea and in no way definite. Any comments on the design or implementation ideas? @lbarman?

**Comment by lbarman** [comment]
Thanks for the input!
Nice idea for the "zoomable" part - somehow I though you could use "tabs" on the top bar to switch between views.
I also like the idea of drag-n-drop (let's see how the browser handle this with an animated SVG element inside)

No clues yet on flexboxes : I'm familiar with bootstrap, I think we can do what (I / we) have in mind with it; hence right now I don't see the urgency of switching, I would prioritize getting a first working plateform.

I also had some sketches, I will post them tomorrow. stay tuned ;)

**Comment by chernetsov** [comment]
Folks,

great starting point!

my 50 cents:

I've already had a chance to play with non-web tools like qgroundcontrol & apm planner and they all look like the tools that at some point got overwhelmed with features in uncontrolled way and hense started to look clunky and ugly.

I suggest that now it's a good moment to figure out the top priority use cases we want to use the tool for and build UIs based on that. How do you plan to use the tool?

Your thoughts? :)

**Comment by jodersky** [comment]
thanks for your prompt feedback,

I had originally envisioned Virtual Flight Deck to be, as the name says, a virtual cockpit for drones. It should display only vital information to the pilot, as if she/he were on an actual aircraft. Therefore I suggest we stick to this general guideline when designig the UI: ask yourself would an actual cockpit have/need this?

In my opinion (I am no pilot) the most important parts of an actual cockpit and their corresponding ui are

| Real Cockpit Part | Virtual Part |
| --- | --- |
| window | video feed |
| primary flight display | instrumentation including attitude, heading and altitude |
| engine controls | information on current motor load, RPM, etc... |
| fuel indicator | battery indicator |
| communication panel | information on the link to the drone such as packet loss rssi etc... |
| autopilot controls | map and mission planning |

The pilot could position these parts to their liking in the normal view but the main point is to leave out any clutter and display only the above information. When user interaction is required, the detailed view would be used, thus still giving an overview of the most vital information to the pilot.

As an example, consider a drone flying a mission. During operation, the pilot should not have to worry about details of the mission, only the current position should be displayed on a map, along with the other above mentioned UI parts. Now, consider the pilot or an assistant wants to change the mission on the fly. This would require them to open the detailed view displaying a mission planner for a brief moment. However, during the mission change, the pilot can still see the most critical information in the right panel.

Regarding the implementation, @lbarman, I'm currently experimenting with flexboxes and the more I look at them the more I think they are the correct way to go. However, note that they would only be used for scaffolding, the actual UI styling would be unchanged.

**Comment by lbarman** [comment]
hi @chernetsov !

OK for flexboxes, I'll look into it. Unfortunately I'm still on the low-result high-investiment part of the scalajs' learning curve, hopefully it will get better soon :)

ACK for your vision of the cockpit, although I agree it makes sense, lemme suggest something : 

# Cockpit proposition

I would have conceived the cockpit by order of importance, following the order of reading a webpage : Most important stuff on the top left, less important towards the bottom right.

![Cockpit sketch](http://i.imgur.com/8p4SPdz.png)
Or in a more readable way maybe ;)
![Cockpit diagram](http://i.imgur.com/chLAraR.png)

Hence I would put the tools in that order :
**CRITICAL** : Link (Ping, Last heartbeat), Flight Time elapsed, Battery Voltage (on a log graph with the expected time on x, voltage on y)

**INTERNALS** : The nice "view from above" you made @jodersky , with the four motors and the XY inclinaison; I would also put an "Distance to ground" graph, that might be accurate between 0-10m, then say "Above 10m", with an arrow indicating the (positive or negative) speed. This might be useful for landing

**NAVIGATION** : Classical compass, Altimeter, And front inclinaison that you find in every plane

**CRITICAL OPS** : A few buttons that triggers an important command in the drone, such as "STOP AND HOLD POSITION", "LAND NOW", "FLY NOW", which we might need at any time (manual emergency feedback)

The rest is pretty self explanatory, with

**ROUTE** : I meant route planning, I would like to be able to input "MoveTo(X, Y, Z)" or something to plan the next action of the drone. Since this is less real-time, I see this at the right of the page

# UX

All those "boxes" borders would be in grey, and would start flashing to draw attention in case of emergency : The **CRITICAL** box might flash if we skip a heartbeat, the **INTERNALS** if Altitude < 10m and Speed < -X m/s, and so on

# Merging the two cockpits

I wait for your feedback guys!

**Comment by jodersky** [comment]
Nice pictures :)
I like your general ideas of positioning stuff, however I would remove the critical info box and keep all logically related information regrouped (i.e. move battery info to internal). However, to still give the user an immediate overview of any warnings or alerts, we could add a thin overview panel (the "well" that was useless until now, see pictures below).
Anyway, we can easily experiment with positioning elements later.

On my side I implemented a proof-of-concept, as you can see in the screenshoits below, using flexboxes.
![normal](https://cloud.githubusercontent.com/assets/1007012/6832279/b6d464cc-d325-11e4-8886-9bbaa71d32e5.png)
![detailed](https://cloud.githubusercontent.com/assets/1007012/6832282/b82e5f30-d325-11e4-9224-55fbf38d20c6.png)
You can see a live demo [here](http://vfd.herokuapp.com/regions) or you can checkout my [branch](https://github.com/jodersky/vfd/tree/design/regions).

Regarding the UX, I am totally open to maximizing any html5 technology, I could even imagine using `<audio>` to sound an alarm if something bad is happening :)

How about I clean up and merge the scaffolding and you take care of the UX, @lbarman? I recall you already did some stylistic work on your fork.
By the way, currently the UI relies on bootstrap since that is what I used to get started. If you think another or no framework would be appropriate, feel free to discuss.

**Comment by lbarman** [comment]
:+1: for flexboxes, I'm convinced ;)
